# Generated by Django 4.1.5 on 2023-01-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('IN USE', 'In Use'), ('REPAIR', 'Repair'), ('DESTROYED', 'Destroyed')], max_length=100, null=True),
        ),
    ]
