# Generated by Django 4.1.5 on 2023-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0002_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('in_use', 'In Use'), ('repair', 'Repair'), ('destroyed', 'Destroyed')], max_length=100, null=True),
        ),
    ]
