# Generated by Django 4.1.5 on 2023-01-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0006_supplier_item_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='data_loader.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='data_loader.category'),
        ),
    ]
