# Generated by Django 4.1.5 on 2023-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0009_item_last_movement_movement_movement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='trello',
            field=models.TextField(blank=True, null=True),
        ),
    ]
