# Generated by Django 4.1.5 on 2023-01-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0011_rename_person_movement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('creation', 'Creation'), ('transfer', 'Transfer'), ('repair', 'Repair'), ('dispose', 'Dispose')], max_length=100, null=True),
        ),
    ]
