# Generated by Django 4.1.5 on 2023-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0012_movement_comment_alter_movement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='disposed_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='in_use_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='repair_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='total_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
