# Generated by Django 4.1.5 on 2023-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0014_location_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='available_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='disposed_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='in_use_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='repair_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
